In [2]:
import torch

x = torch.empty(5, 3)
print(x)

tensor([[0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 9.1084e-44, 0.0000e+00],
        [1.1896e+19, 3.0760e-41, 1.6249e-15]])


In [3]:
x = torch.rand(5, 3)

In [4]:
print(x)

tensor([[0.8938, 0.4845, 0.5031],
        [0.5049, 0.7561, 0.0857],
        [0.1289, 0.2966, 0.6657],
        [0.7509, 0.8692, 0.4318],
        [0.6741, 0.8020, 0.2236]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)

In [6]:
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])

In [8]:
print(x)

tensor([5.5000, 3.0000])


In [9]:
x = x.new_ones(5, 3, dtype=torch.double)

In [10]:
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)

In [13]:
print(x)

tensor([[-0.2781,  0.9380,  0.3332],
        [-2.2800, -0.7043, -1.6044],
        [-0.2775,  1.5001,  1.2569],
        [-1.3753, -0.3705,  1.2215],
        [-0.7759,  0.0259,  0.5522]])


In [14]:
x.size()

torch.Size([5, 3])

In [16]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0188,  1.6700,  0.8443],
        [-1.7783,  0.1306, -0.7851],
        [ 0.6520,  2.1400,  1.5698],
        [-0.6880,  0.6023,  1.8914],
        [-0.5627,  0.6876,  0.7655]])


In [17]:
print(torch.add(x, y))

tensor([[-0.0188,  1.6700,  0.8443],
        [-1.7783,  0.1306, -0.7851],
        [ 0.6520,  2.1400,  1.5698],
        [-0.6880,  0.6023,  1.8914],
        [-0.5627,  0.6876,  0.7655]])


In [18]:
result = torch.empty(5, 3)
torch.add(x, y , out=result)
result

tensor([[-0.0188,  1.6700,  0.8443],
        [-1.7783,  0.1306, -0.7851],
        [ 0.6520,  2.1400,  1.5698],
        [-0.6880,  0.6023,  1.8914],
        [-0.5627,  0.6876,  0.7655]])

In [19]:
y.add(x)
y

tensor([[0.2592, 0.7320, 0.5111],
        [0.5017, 0.8349, 0.8194],
        [0.9295, 0.6399, 0.3128],
        [0.6873, 0.9728, 0.6699],
        [0.2131, 0.6617, 0.2133]])

In [20]:
y.add_(x)
y

tensor([[-0.0188,  1.6700,  0.8443],
        [-1.7783,  0.1306, -0.7851],
        [ 0.6520,  2.1400,  1.5698],
        [-0.6880,  0.6023,  1.8914],
        [-0.5627,  0.6876,  0.7655]])

In [21]:
x

tensor([[-0.2781,  0.9380,  0.3332],
        [-2.2800, -0.7043, -1.6044],
        [-0.2775,  1.5001,  1.2569],
        [-1.3753, -0.3705,  1.2215],
        [-0.7759,  0.0259,  0.5522]])

In [22]:
print(x[:, 1])

tensor([ 0.9380, -0.7043,  1.5001, -0.3705,  0.0259])


In [23]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [24]:
y

tensor([ 1.0631,  0.1839, -0.3365,  0.8719,  0.8929, -1.7967,  0.0450,  0.9862,
        -0.1719,  0.5987, -0.6779, -1.9255,  0.0501, -0.0246,  0.3217,  0.2706])

In [25]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8942])
-0.8942199945449829
